# -*- coding: utf-8 -*-
"""Assessment_Machine_Learning.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1aaXJqguajU9FtrNuOywxLcTUK3TFuxnj

Question 1. How to Implement the KNN Classification Algorithm ?
"""

import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import accuracy_score

df = pd.read_csv("customer_churn.csv")
df.head()

#Label Encoding
from sklearn.preprocessing import LabelEncoder
lcoder = LabelEncoder()
df['Churn'] = lcoder.fit_transform(df['Churn'])

x = df[['MonthlyCharges']]
y = df['Churn']

#Train and Test Split
x_train, x_test, y_train, y_test = train_test_split(x, y,test_size=0.3, random_state=42)

#Standard Scaler
scaler = StandardScaler()
X_train = scaler.fit_transform(x_train)
X_test = scaler.transform(x_test)

#KNN Model
KNN = KNeighborsClassifier(n_neighbors=5)
Knn_model = KNN.fit(x_train,y_train)

y_pred = Knn_model.predict(x_test)

accuracy = accuracy_score(y_test, y_pred)
print("KNN Accuracy:", accuracy)



"""Question 2. Build a logistic regression model on the ‘customer churn’ dataset in Python. The dependent variable is ‘Churn’ and the independent variable is ‘Monthly Charges.’ Find the log loss of the model."""

import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import log_loss
from sklearn.preprocessing import LabelEncoder

#Load Data
df = pd.read_csv("customer_churn.csv")
df.head()

#Label Encoding
lcoder = LabelEncoder()
df['Churn'] = lcoder.fit_transform(df['Churn'])

x = df[['MonthlyCharges']]
y = df['Churn']

#Split the data into training and testing sets
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.3, random_state=42)

#Logistic Regression Model
Logistic_Regression = LogisticRegression()
LR_model = Logistic_Regression.fit(x_train,y_train)

# Predict probabilities
y_pre = LR_model.predict_proba(x_test)

# Calculate Log Loss
loss = log_loss(y_test, y_pred)
print("Log Loss:", loss)

